run:
  name: "Run"
  description: "Run Command"
  fields:
    command:
      name: "Command"
      description: "Command"
      required: true
      default: 'echo hello world!'
      selector:
        text:
    timeout:
      name: "Timeout"
      description: "Timeout (seconds)"
      required: true
      default: 10
      selector:
          number:
            min: 1
            max: 300